name: ChatManager
version: 0.1.0
author: mouseymars
description: A simple plugin that allows you to manage your servers chat
main: net.aidantaylor.bukkit.chatmanager.Main
softdepend: [Vault, LilyPad-Connect]
commands:
   chatmanager:
      description: Main command for all 'chatmanager' commands
      aliases: [cm, chatm, chat, cmanager]
permissions:
   chatmanager.chat:
       description: Allows a player to talk in chat
       default: true
   chatmanager.chat.override:
       description: Allows players to talk when chat is restricted
       default: op
   chatmanager.chat.colour:
       description: Allows players to do coloured chat
       default: op
   chatmanager.chat.format:
       description: Allows players to do formatted chat
       default: op
   chatmanager.chat.magic:
       description: Allows players to do magic chat
       default: op
   chatmanager.ranged.override:
       description: allows a player to view chats past the ranged limit
       default: op
   chatmanager.chat.hideshow:
       description: Allows players to toggle if they see the chat
       default: op
   chatmanager.chat.ding:
       description: Allows players to be notified when they're mentioned
       default: op
   chatmanager.chat.mode:
       description: Allows players to change chat mode
       default: op
   chatmanager.chat.mode.on:
       description: Allows players to turn the whole chat on and off
       default: op
   chatmanager.chat.mode.restricted:
       description: Allows players to turn chat into restricted mode
       default: op